### ISSUE TITLE
Framerate drops to unplayable levels.

### ISSUE THREAD

**Issue by ZenDragonX** [RustyMods/RustyCompass#1]
Every time I install this mod I get horrible framerate drops to 5fps.  I would love to try it but I can't figure out why this is happening.  I sure hope this is easy to fix, the mod looks cool! :)

**Comment by RustyMods** [comment]
Hmm first I hear of compass causing fps drop. Come find me on Odin plus discord so we can pm and I'll help troubleshoot your issues. Might be a conflict somehow with another plugin. 

Else, only thing that might cause fps drop would be the tame tracker feature. Which is disabled by default.

**Comment by ZenDragonX** [comment]
Ahh, yes I think you are correct.  I did a bit more testing and it wasn't your mod.  Sorry for the confusion.
